import hashlib
import os
from pathlib import Path
from typing import Dict, Optional, Tuple

import pandas as pd
import streamlit as st

import testimonial_pipeline as pipeline

DEFAULT_CACHE_PATH = "master_testimonial_cache.csv"
RESULT_STATE_KEY = "analysis_result"


def default_api_key() -> str:
    try:
        if "GEMINI_API_KEY" in st.secrets:
            return str(st.secrets["GEMINI_API_KEY"])
    except Exception:
        pass
    return os.environ.get("GEMINI_API_KEY", "")


def uploaded_file_signature(uploaded_file) -> str:
    if uploaded_file is None:
        return "none"
    payload = uploaded_file.getvalue()
    return f"{uploaded_file.name}:{len(payload)}:{hashlib.sha256(payload).hexdigest()}"


def build_run_signature(
    uploaded_testimonials,
    uploaded_cache,
    *,
    model: str,
    local_cache_path: str,
    force_reprocess: bool,
    max_rows: int,
) -> str:
    signature_parts = [
        uploaded_file_signature(uploaded_testimonials),
        uploaded_file_signature(uploaded_cache),
        model,
        local_cache_path,
        str(force_reprocess),
        str(max_rows),
    ]
    return "||".join(signature_parts)


def render_results(result_state: Dict[str, object]) -> None:
    visible_output = result_state["visible_output"]
    output_with_internal = result_state["output_with_internal"]
    updated_cache = result_state["updated_cache"]
    saved_path = result_state.get("saved_path")

    success_message = f"Generated {len(visible_output)} scored rows."
    if saved_path:
        success_message += f" Updated cache written to `{saved_path}`."
    st.success(success_message)

    summary_cols = st.columns(5)
    summary_cols[0].metric("Analysis OK Rows", int((output_with_internal["analysis_status"] == "ok").sum()))
    summary_cols[1].metric("Quote Rows With Output", int(output_with_internal["quote_status"].apply(pipeline.quote_status_is_ok).sum()))
    summary_cols[2].metric("Marketing Ready Quotes", int(output_with_internal["quote_marketing_ready"].fillna(False).sum()))
    summary_cols[3].metric("Case Study Ready Quotes", int(output_with_internal["quote_case_study_ready"].fillna(False).sum()))
    summary_cols[4].metric("Manual Review Rows", int(output_with_internal["manual_review_required"].fillna(False).sum()))

    st.subheader("Scored Upload Preview")
    preview_cols = [
        "Response ID",
        "Study subject",
        "overall_sentiment_score_0_100",
        "overall_sentiment_label",
        "overall_feedback_summary_1_sentence",
        "quote_status",
        "quote_marketing_ready",
        "manual_review_required",
    ]
    preview_cols = [column for column in preview_cols if column in visible_output.columns]
    st.dataframe(visible_output[preview_cols].head(50), use_container_width=True, hide_index=True)

    download_col_1, download_col_2 = st.columns(2)
    with download_col_1:
        st.download_button(
            "Download Scored Upload CSV",
            data=df_to_csv_bytes(visible_output),
            file_name="testimonials_scored_output.csv",
            mime="text/csv",
        )
    with download_col_2:
        st.download_button(
            "Download Updated Master Cache CSV",
            data=df_to_csv_bytes(updated_cache),
            file_name="master_testimonial_cache.csv",
            mime="text/csv",
        )


def df_to_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode("utf-8")


def render_field_dictionary() -> None:
    dictionary_df = pipeline.generated_field_dictionary_df(include_cache_only=True)
    with st.expander("Generated Field Descriptions", expanded=False):
        st.caption("Only fields generated by the app are listed here. Your original upload columns are not included.")
        st.dataframe(dictionary_df, use_container_width=True, hide_index=True)
        st.download_button(
            "Download Field Dictionary CSV",
            data=df_to_csv_bytes(dictionary_df),
            file_name="generated_field_dictionary.csv",
            mime="text/csv",
            key="download_generated_field_dictionary",
        )


def load_cache_source(uploaded_cache, local_cache_path: str) -> Tuple[pd.DataFrame, str]:
    if uploaded_cache is not None:
        return pd.read_csv(uploaded_cache), "uploaded cache"

    cache_path = Path(local_cache_path)
    if cache_path.exists():
        return pd.read_csv(cache_path), f"local file: {cache_path}"

    return pd.DataFrame(), "empty cache"


def split_upload_vs_cache(
    prepared_upload_df: pd.DataFrame,
    cache_df: pd.DataFrame,
    force_reprocess: bool,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    prepared_unique = prepared_upload_df.drop_duplicates(subset=pipeline.MATCH_COLUMNS, keep="first").copy()
    cache_ready = pipeline.normalize_existing_cache_df(cache_df)

    cache_row_key_view = cache_ready[["row_key", "content_hash", "pipeline_version"]].drop_duplicates(subset=["row_key"], keep="last")

    diagnostics = prepared_unique[["row_key", "content_hash", "pipeline_version"]].merge(
        cache_row_key_view,
        on="row_key",
        how="left",
        suffixes=("_upload", "_cache"),
    )
    diagnostics["cache_status"] = "new"
    exact_mask = (
        diagnostics["content_hash_cache"].notna()
        & diagnostics["content_hash_upload"].eq(diagnostics["content_hash_cache"])
        & diagnostics["pipeline_version_cache"].eq(diagnostics["pipeline_version_upload"])
    )
    changed_mask = diagnostics["content_hash_cache"].notna() & ~exact_mask
    diagnostics.loc[exact_mask, "cache_status"] = "cached_exact"
    diagnostics.loc[changed_mask, "cache_status"] = "changed_or_stale"

    if force_reprocess:
        reusable = pd.DataFrame(columns=pipeline.MATCH_COLUMNS + pipeline.RESULT_COLUMNS)
        to_process = prepared_unique
    else:
        reusable = prepared_unique.merge(
            pipeline.reusable_cache_subset(cache_ready),
            on=pipeline.MATCH_COLUMNS,
            how="inner",
        )
        reusable_keys = reusable[pipeline.MATCH_COLUMNS].drop_duplicates()
        to_process = prepared_unique.merge(reusable_keys, on=pipeline.MATCH_COLUMNS, how="left", indicator=True)
        to_process = to_process[to_process["_merge"] == "left_only"].drop(columns="_merge")

    return reusable, to_process, diagnostics


def persist_cache_if_requested(cache_df: pd.DataFrame, persist_local: bool, local_cache_path: str) -> Optional[str]:
    if not persist_local:
        return None

    cache_path = Path(local_cache_path)
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    cache_df.to_csv(cache_path, index=False)
    return str(cache_path)


def main() -> None:
    st.set_page_config(page_title="Testimonial Sentiment Analysis", layout="wide")

    st.title("Testimonial Sentiment Analysis")
    st.write(
        "Upload a testimonials CSV, reuse a master cache CSV for prior results, "
        "and only send new or changed rows for analysis."
    )

    with st.sidebar:
        st.subheader("Settings")
        api_key = st.text_input(
            "Gemini API key",
            value=default_api_key(),
            type="password",
            help="Required for rows that are not already in the cache.",
        )
        model = st.text_input("Model", value=pipeline.MODEL_DEFAULT)
        local_cache_path = st.text_input("Local master cache path", value=DEFAULT_CACHE_PATH)
        persist_local = st.checkbox(
            "Write updated cache to local file",
            value=True,
            help="Useful locally. On Streamlit Community Cloud, generated files are not guaranteed to persist across sessions or reboots.",
        )
        force_reprocess = st.checkbox("Force reprocess uploaded rows", value=False)
        max_rows = st.number_input(
            "Max rows to process",
            min_value=0,
            value=0,
            step=1,
            help="Set to 0 to use the full upload. Any positive value limits testing to the first N rows.",
        )

    upload_col, cache_col = st.columns(2)
    with upload_col:
        uploaded_testimonials = st.file_uploader("Testimonials CSV", type=["csv"])
    with cache_col:
        uploaded_cache = st.file_uploader("Existing master cache CSV (optional)", type=["csv"])

    render_field_dictionary()

    if uploaded_testimonials is None:
        st.info("Upload a testimonials CSV to begin.")
        return

    current_run_signature = build_run_signature(
        uploaded_testimonials,
        uploaded_cache,
        model=model,
        local_cache_path=local_cache_path,
        force_reprocess=force_reprocess,
        max_rows=int(max_rows),
    )
    result_state = st.session_state.get(RESULT_STATE_KEY)
    has_current_results = bool(result_state and result_state.get("run_signature") == current_run_signature)

    try:
        input_df = pd.read_csv(uploaded_testimonials)
    except Exception as exc:
        st.error(f"Could not read testimonials CSV: {exc}")
        return

    original_uploaded_rows = len(input_df)
    if max_rows > 0:
        input_df = input_df.head(int(max_rows)).copy()

    prepared_upload = pipeline.prepare_input_df(input_df)
    cache_df, cache_source = load_cache_source(uploaded_cache, local_cache_path)
    reusable, to_process, diagnostics = split_upload_vs_cache(prepared_upload, cache_df, force_reprocess)

    stats = st.columns(4)
    stats[0].metric("Uploaded Rows", len(prepared_upload))
    stats[1].metric("Reusable Cached Rows", int((diagnostics["cache_status"] == "cached_exact").sum()))
    stats[2].metric("Changed / Stale Rows", int((diagnostics["cache_status"] == "changed_or_stale").sum()))
    stats[3].metric("Rows To Analyze", len(to_process))

    st.caption(f"Cache source: {cache_source}")
    if max_rows > 0:
        st.caption(
            f"Test mode active: processing the first {len(prepared_upload)} rows from an upload of {original_uploaded_rows} rows."
        )
    st.caption(
        "For Streamlit Community Cloud, treat the downloaded master cache CSV as the source of truth. "
        "Local files created by the app are not guaranteed to persist."
    )

    with st.expander("Preview cache matching", expanded=False):
        st.dataframe(
            diagnostics[["row_key", "cache_status"]].head(50),
            use_container_width=True,
            hide_index=True,
        )

    run_clicked = st.button("Run Analysis", type="primary")
    if run_clicked:
        if len(to_process) > 0 and not api_key.strip():
            st.error("Enter a Gemini API key to analyze rows that are not already in the cache.")
            return

        progress_bar = st.progress(0)
        status_text = st.empty()

        try:
            if len(to_process) > 0:
                def on_progress(done: int, total: int, row_label: str) -> None:
                    progress_bar.progress(done / max(total, 1))
                    status_text.write(f"Analyzing row {done}/{total}: `{row_label}`")

                fresh_results = pipeline.analyse_rows(
                    to_process,
                    api_key=api_key,
                    model=model,
                    progress_callback=on_progress,
                )
            else:
                fresh_results = pd.DataFrame(columns=pipeline.MATCH_COLUMNS + pipeline.RESULT_COLUMNS)
                progress_bar.progress(1.0)
                status_text.write("All uploaded rows were already covered by the cache.")

            reusable_results = reusable[pipeline.MATCH_COLUMNS + pipeline.RESULT_COLUMNS].copy()
            all_results = pd.concat([reusable_results, fresh_results], ignore_index=True)
            output_with_internal = pipeline.merge_results_into_upload(prepared_upload, all_results)
            visible_output = pipeline.strip_internal_columns(output_with_internal)

            updated_cache = pipeline.upsert_master_cache(cache_df, output_with_internal)
            saved_path = persist_cache_if_requested(updated_cache, persist_local, local_cache_path)

        except Exception as exc:
            progress_bar.empty()
            status_text.empty()
            st.error(f"Analysis failed: {exc}")
            st.exception(exc)
            return

        progress_bar.progress(1.0)
        status_text.write("Analysis complete.")
        st.session_state[RESULT_STATE_KEY] = {
            "run_signature": current_run_signature,
            "visible_output": visible_output,
            "output_with_internal": output_with_internal,
            "updated_cache": updated_cache,
            "saved_path": saved_path,
        }
        result_state = st.session_state[RESULT_STATE_KEY]
        has_current_results = True

    if has_current_results:
        render_results(result_state)
    elif RESULT_STATE_KEY in st.session_state:
        st.info("Inputs changed since the last run. Click `Run Analysis` to refresh the preview and download files.")


if __name__ == "__main__":
    main()
